#!/usr/bin/env bash

# Convenience script to run the etherspot binary from built source
#
# ./safehodl standalone --redirectRpc

node --experimental-specifier-resolution=node ./packages/cli/bin/safehodl.js "$@"